name: C/C++ CI

on:
  push:
    branches: [ "main", "feature/**", "fix/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        std: [c++20, c++23]
        cxx: [g++-12, clang++-16]
        include:
          - std: c++2b
            cxx: clang++-15
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev ${{ matrix.cxx }}
    - name: build tests
      run: make -C test -j$(nproc) CXX=${{ matrix.cxx }} STD=${{ matrix.std }}  
    - name: run tests
      run: make -C test -j$(nproc) CXX=${{ matrix.cxx }} STD=${{ matrix.std }} run-tests 
